spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${host.ip}:3309/hjb_blog?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      web-stat-filter:
        session-stat-enable: false
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    port: 6336
    host: ${host.ip}
    password: 123456

  banner:
    charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true

mybatis:
  type-aliases-package: com.hjb.syllabus.entity.po
  mapper-locations: classpath:mapper/*.xml
host:
  ip: 120.77.215.148
  tableUrl: https://www.chiyouyun.com/kb/